name: "HProvider Client"
version: "1.0"
client:
    organization: HProvider
    credentialStore:
    path: "./hfc-key-store"
    cryptoStore:
      path: "./hfc-key-store"
    channels:
        healthchannel:
            orderers:
            - ordererhp.healthcare.com
        peers:
            peer0.hprovider.healthcare.com:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            peer0.research.healthcare.com:
                endorsingPeer: true
                chaincodeQuery: false
                ledgerQuery: true
                eventSource: false
    organizations:
        HProvider:
            mspid: HProviderMSP
            peers:
            - peer0.hprovider.healthcare.com
            - peer1.hprovider.healthcare.com
            - peer2.hprovider.healthcare.com
        certificateAuthorities:
            - ca.hprovider.healthcare.com
        adminPrivateKey:
            path: ../crypto-config/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp/keystore/*_sk
        signedCert:
            path: crypto-config/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp/signcerts/Admin@hprovider.healthcare.com-cert.pem
    orderers:
       ordererhp.healthcare.com:
            url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: ordererhp.healthcare.com
      grpc-max-send-message-length: 15
    tlsCACerts:
      path: crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    peers:
        peer0.hprovider.healthcare.com:
            url: grpcs://localhost:7051
            eventUrl: grpcs://localhost:7053
            grpcOptions:
            ssl-target-name-override: peer0.hprovider.healthcare.com
            grpc.keepalive_time_ms: 600000
            tlsCACerts:
            path: crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/msp/tlscacerts/tlsca.hprovider.healthcare.com-cert.pem  
        peer1.hprovider.healthcare.com:
            url: grpcs://localhost:8051
            eventUrl: grpcs://localhost:8053
            grpcOptions:
            ssl-target-name-override: peer1.hprovider.healthcare.com
            grpc.keepalive_time_ms: 600000
            tlsCACerts:
            path: crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp/tlscacerts/tlsca.hprovider.healthcare.com-cert.pem
        peer2.hprovider.healthcare.com:
            url: grpcs://localhost:8051
            eventUrl: grpcs://localhost:8053
            grpcOptions:
            ssl-target-name-override: peer1.hprovider.healthcare.com
            grpc.keepalive_time_ms: 600000
            tlsCACerts:
            path: crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp/tlscacerts/tlsca.hprovider.healthcare.com-cert.pem
    certificateAuthorities:
        ca.hprovider.healthcare.com:
            url: https://localhost:7054
            httpOptions:
            verify: false
            tlsCACerts:
            path: crypto-config/peerOrganizations/hprovider.healthcare.com/ca/ca.hprovider.healthcare.com-cert.pem
            registrar:
            - enrollId: admin
                enrollSecret: adminpw
        caName: ca.hprovider.healthcare.com
            ca.hprovider.healthcare.com:
                url: https://localhost:7054
                httpOptions:
                verify: false
                tlsCACerts:
                path: crypto-config/peerOrganizations/hprovider.healthcare.com/ca/ca.hprovider.healthcare.com-cert.pem
                registrar:
                - enrollId: admin
                    enrollSecret: adminpw
                caName: ca.hprovider.healthcare.com