################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
   
    - &Orderer        
        Name: Orderer
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/healthcare.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &HProvider        
        Name: HProviderMSP
        ID: HProviderMSP
        MSPDir: crypto-config/peerOrganizations/hprovider.healthcare.com/msp
        AnchorPeers:
            - Host: peer0.hprovider.healthcare.com
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HProviderMSP.admin', 'HProviderMSP.peer', 'HProviderMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HProviderMSP.admin', 'HProviderMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HProviderMSP.admin')"

    - &Research        
        Name: ResearchMSP
        ID: ResearchMSP
        MSPDir: crypto-config/peerOrganizations/research.healthcare.com/msp
        AnchorPeers:
            - Host: peer0.research.healthcare.com
              Port: 7051
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ResearchMSP.admin', 'ResearchMSP.peer', 'ResearchMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ResearchMSP.admin', 'ResearchMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ResearchMSP.admin')"
    

    
################################################################################
#
#   SECTION: Capabilities
#
#
################################################################################
Capabilities:    
    Global: &ChannelCapabilities        
        V1_1: true
    
    Orderer: &OrdererCapabilities        
        V1_1: true
    
    Application: &ApplicationCapabilities        
        V1_2: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults


    OrdererType: solo

    Addresses:
        - orderer.healthcare.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092

  
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    HealthOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            HealthConsortium:
                Organizations:
                    - *HProvider
                    - *Research
    HealthChannel:
        Consortium: HealthConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *HProvider
                - *Research  

#peer channel create -c healthchannel -o orderer.healthcare.com:7050