OrdererOrgs:
  - Name: Orderer
    Domain: healthcare.com
    Specs:
    - Hostname: orderer
PeerOrgs:
  - Name: HProvider
    Domain: hprovider.healthcare.com
    Template:
      Count: 3
    Users:
      Count: 3
  # - Name: Research
  #   Domain: research.healthcare.com
  #   Template:
  #     Count: 3
  #   Users:
  #     Count: 3
  # - Name: Patient
  #   Domain: patient.healthcare.com
  #   Template:
  #     Count: 3
  #   Users:
  #     Count: 3