# 
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererHp
    Domain: healthcare.com    
    Specs:
      - Hostname: ordererhp
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Healthcare Provider
  # ---------------------------------------------------------------------------
  - Name: HProvider
    Domain: hprovider.healthcare.com 
    EnableNodeOUs: true
    
    Template:
      Count: 4
       
    Users:
      Count: 4
  # ---------------------------------------------------------------------------
  # Research
  # ---------------------------------------------------------------------------
  # - Name: Research
  #   Domain: research.healthcare.com 
  #   EnableNodeOUs: true
  #   Template:
  #     Count: 4
  #   Users:
  #     Count: 4
  # ---------------------------------------------------------------------------
 