#

version: '2'

volumes:
  ordererhp.healthcare.com:
  peer0.hprovider.healthcare.com:
  peer1.hprovider.healthcare.com:
  peer0.research.healthcare.com:
  peer1.research.healthcare.com:

networks:
  healthNetwork:

services:
  ordererhp.healthcare.com:
    container_name: ordererhp.healthcare.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererHpMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/healthcare.com/orderers/ordererhp.healthcare.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/healthcare.com/orderers/ordererhp.healthcare.com/tls/:/var/hyperledger/orderer/tls
      - ordererhp.healthcare.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050    
    networks:
      - healthNetwork

  ca.hprovider.healthcare.com:
      container_name: ca.hprovider.healthcare.com
      image: hyperledger/fabric-ca:$IMAGE_TAG
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.hprovider.health.com
        # - FABRIC_CA_SERVER_REGISTRY_MAXENROLLMENTS=1 # only allow to register one admin
        - FABRIC_CA_SERVER_CA_CERTFILE=./crypto-config/peerOrganizations/hprovider.healthcare.com/ca/ca.hprovider.healthcare.com-cert.pem # default $HOME/ca-key.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=./crypto-config/peerOrganizations/hprovider.healthcare.com/ca/fdea3862fc578eb0510c21cc7fc7895d73f8b605d6c99e0014a439f178376469_sk # default $HOME/ca-cert.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=$CA_TLS_ENABLED # default tls cert $HOME/tls-cert.pem
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_CERTFILES=
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem
      ports:
            - 7054:7054
          # -b :bootstrap identity is required to start the Fabric CA server; this identity is the server administrator.
      command: sh -c 'fabric-ca-server start -b admin:adminpw'
      volumes:
        - ./crypto-config/peerOrganizations/hprovider.health.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      networks:
        - healthNetwork

  ca.research.healthcare.com:
      container_name: ca.research.healthcare.com
      image: hyperledger/fabric-ca:$IMAGE_TAG
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.research.healthcare.com
        - FABRIC_CA_SERVER_REGISTRY_MAXENROLLMENTS=1 # only allow to register one admin
        - FABRIC_CA_SERVER_CA_CERTFILE=./crypto-config/peerOrganizations/research.healthcare.com/ca/ca.research.healthcare.com-cert.pem # default $HOME/ca-key.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=./crypto-config/peerOrganizations/research.healthcare.com/ca/350762a6d88c65237927c057a100f018ce37fd7bddcf08a5a4b26ceaefe93ade_sk # default $HOME/ca-cert.pem 
        - FABRIC_CA_SERVER_TLS_ENABLED=$CA_TLS_ENABLED # default tls cert $HOME/tls-cert.pem
          # - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=
          # - FABRIC_CA_SERVER_TLS_CLIENTAUTH_CERTFILES=
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem
      ports:
        - 8054:7054
      command: sh -c 'fabric-ca-server start -b admin:adminpw'
      volumes:
        - ./crypto-config/peerOrganizations/research.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      networks:
        - healthNetwork

  peer0.hprovider.healthcare.com:
    container_name: peer0.hprovider.healthcare.com
    extends:
     file: peer-base.yaml
     service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hprovider.healthcare.com
      - CORE_PEER_ADDRESS=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hprovider.healthcare.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=HProviderMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hprovider.healthcare.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    networks:
      - healthNetwork

  peer1.hprovider.healthcare.com:
    container_name: peer1.hprovider.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hprovider.healthcare.com
      - CORE_PEER_ADDRESS=peer1.hprovider.healthcare.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hprovider.healthcare.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=HProviderMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hprovider.healthcare.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053
    networks:
      - healthNetwork

  peer0.research.healthcare.com:
    container_name: peer0.research.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.research.healthcare.com
      - CORE_PEER_ADDRESS=peer0.research.healthcare.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.research.healthcare.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.research.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=ResearchMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0.research.healthcare.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053
    networks:
      - healthNetwork

  peer1.research.healthcare.com:
    container_name: peer1.research.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.research.healthcare.com
      - CORE_PEER_ADDRESS=peer1.research.healthcare.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.research.healthcare.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.research.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=ResearchMSP
    volumes:
        - /var/run/:/host/var/run/        
        - ./crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.research.healthcare.com:/var/hyperledger/production
    networks:
      - healthNetwork
        
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=HProviderMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/        
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config/        
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
    depends_on:
      - ordererhp.healthcare.com
      - peer0.hprovider.healthcare.com
      - peer1.hprovider.healthcare.com
      - peer0.research.healthcare.com
      - peer1.research.healthcare.com

    networks:
      - healthNetwork
