# Blockchain by example - food supply chain
---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/healthcare.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &HProvider
        Name: HProviderMSP
        ID: HProviderMSP
        MSPDir: crypto-config/peerOrganizations/hprovider.healthcare.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HProviderMSP.admin', 'HProviderMSP.peer', 'HProviderMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HProviderMSP.admin', 'HProviderMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HProviderMSP.admin')"

        AnchorPeers:
            - Host: peer0.hprovider.healthcare.com
              Port: 7051

    - &Research
        Name: ResearchMSP
        ID: ResearchMSP
        MSPDir: crypto-config/peerOrganizations/research.healthcare.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ResearchMSP.admin', 'ResearchMSP.peer', 'ResearchMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ResearchMSP.admin', 'ResearchMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ResearchMSP.admin')"

        AnchorPeers:
            - Host: peer0.research.healthcare.com
              Port: 7051

Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses:
        - orderer.healthcare.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 20 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

Application: &ApplicationDefaults

    Organizations:

###############################################################################
#
#   Capabilities
#
################################################################################

Capabilities:    
    Global: &ChannelCapabilities        
        V1_1: true
    
    Orderer: &OrdererCapabilities        
        V1_1: true
    
    Application: &ApplicationCapabilities        
        V1_2: true

###############################################################################
#
#   Profile
#
#   - define HealthOrdererGenesis and HealthChannel
#
################################################################################
Profiles:

    HealthOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            HealthChainConsortium:
                Organizations:
                    - *HProvider
                    - *Research
    HealthChannel:
        Consortium: HealthChainConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *HProvider
                - *Research

