# Blockchain by example
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: healthcare.com
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # HProvider
  # ---------------------------------------------------------------------------
  - Name: HProvider
    Domain: hprovider.healthcare.com
    Template:
      Count: 2
    Users:
      Count: 2
  # ---------------------------------------------------------------------------
  # Org2
  # ---------------------------------------------------------------------------
  - Name: Research
    Domain: research.healthcare.com
    Template:
      Count: 2
    Users:
      Count: 2
