
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererHProvider
    Domain: healthcare.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: ordererhp
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1: A simple organization
  # ---------------------------------------------------------------------------
  - Name: hp1
    Domain: hp1.healthcare.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2: Another simple organization
  # ---------------------------------------------------------------------------
  - Name: hp2
    Domain: hp2.healthcare.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
