version: '2'

volumes: 
  ca.hprovider.healthcare.com:
  ca.research.healthcare.com:
   

networks:
    healthNetwork:

services:
    
    ca.hprovider.healthcare.com:
      container_name: ca.hprovider.healthcare.com
      image: hyperledger/fabric-ca:1.4.0
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.hprovider.health.com
        # - FABRIC_CA_SERVER_REGISTRY_MAXENROLLMENTS=1 # only allow to register one admin
        - FABRIC_CA_SERVER_CA_CERTFILE=./crypto-config/peerOrganizations/hprovider.healthcare.com/ca/ca.hprovider.healthcare.com-cert.pem # default $HOME/ca-key.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=./crypto-config/peerOrganizations/hprovider.healthcare.com/ca/*_sk # default $HOME/ca-cert.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=$CA_TLS_ENABLED # default tls cert $HOME/tls-cert.pem
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_CERTFILES=
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem
      ports:
        - 7054:7054
        # -b :bootstrap identity is required to start the Fabric CA server; this identity is the server administrator.
      command: sh -c 'fabric-ca-server start -b admin:adminpw'
      volumes:
        - ./crypto-config/peerOrganizations/hprovider.health.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      networks:
        - healthNetwork
    
    ca.research.healthcare.com:
      container_name: ca.research.healthcare.com
      image: hyperledger/fabric-ca:1.4.0
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.research.healthcare.com
        # - FABRIC_CA_SERVER_REGISTRY_MAXENROLLMENTS=1 # only allow to register one admin
        - FABRIC_CA_SERVER_CA_CERTFILE=./crypto-config/peerOrganizations/research.healthcare.com/ca/ca.research.healthcare.com-cert.pem # default $HOME/ca-key.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=./crypto-config/peerOrganizations/research.healthcare.com/ca/*_sk # default $HOME/ca-cert.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=$CA_TLS_ENABLED # default tls cert $HOME/tls-cert.pem
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=
        #- FABRIC_CA_SERVER_TLS_CLIENTAUTH_CERTFILES=
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem
      ports:
        - 7056:7054
        # -b :bootstrap identity is required to start the Fabric CA server; this identity is the server administrator.
      command: sh -c 'fabric-ca-server start -b admin:adminpw'
      volumes:
        - ./crypto-config/peerOrganizations/research.health.com/ca/:/etc/hyperledger/fabric-ca-server-config/ca
      networks:
        - healthNetwork
    
    cli:
        container_name: cli
        image: hyperledger/fabric-tools
        tty: true
        dns_search: .
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.hprovider.healthcare.com:7051
          - CORE_PEER_LOCALMSPID=HProviderMSP
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp
          - CORE_CHAINCODE_KEEPALIVE=10
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../chaincode/:/opt/gopath/src/github.com/chaincode/
            - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        depends_on:
          - ca.hprovider.healthcare.com
          - ca.research.healthcare.com
        networks:
          - healthNetwork