version: '3'

volumes: 
  peer0.research.healthcare.com:
  peer1.research.healthcare.com:
   

networks:
    healthNetwork:

services:   
    peer0.research.healthcare.com:
        image: hyperledger/fabric-peer
        container_name: peer0.research.healthcare.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=healthNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=healthNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_LOGGING_GOSSIP=WARNING
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.research.healthcare.com:7053
            - CORE_PEER_ID=peer0.research.healthcare.com
            - CORE_PEER_ADDRESS=peer0.research.healthcare.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.reserach.healthcare.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=ResearchMSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@research.healthcare.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@research.healthcare.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@research.healthcare.com/tls/client.key
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.reserach:9984
        command: peer node start --peer-chaincodedev=true
        volumes:
            - /var/run/:/host/var/run/
            - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            - ../crypto-config/:/var/hyperledger/configs
            - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/research.healthcare.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
        networks:
           - healthNetwork
        ports:
          - 7051:7051
          - 7053:7053 
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $RESEARCH_HOSTNAME

      
    peer1.research.healthcare.com:
        image: hyperledger/fabric-peer
        container_name: peer1.research.healthcare.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=healthNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=healthNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_LOGGING_GOSSIP=WARNING
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.research.healthcare.com:7053
            - CORE_PEER_ID=peer1.research.healthcare.com
            - CORE_PEER_ADDRESS=peer1.research.healthcare.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.reserach.healthcare.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_LOCALMSPID=ResearchMSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@research.healthcare.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@research.healthcare.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@research.healthcare.com/tls/client.key
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.reserach:9984
        volumes:
            - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/research.healthcare.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/configs
        networks:
           - healthNetwork
        ports:
            - 8051:7051
            - 8053:7053
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $RESEARCH_HOSTNAME

    cli:
       container_name: cli
       image: hyperledger/fabric-tools
       tty: true
       environment:
         - GOPATH=/opt/gopath
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - CORE_LOGGING_LEVEL=DEBUG
         - CORE_PEER_ID=cli
         - CORE_PEER_ADDRESS=peer0.research.healthcare.com:7051
         - CORE_PEER_LOCALMSPID=ResearchMSP
         - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/research.healthcare.com/users/Admin@research.healthcare.com/msp
         - CORE_CHAINCODE_KEEPALIVE=10
       working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
       command: /bin/bash
       volumes:
           - /var/run/:/host/var/run/
           - ../../chaincode/:/opt/gopath/src/github.com/chaincode
           - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
           - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
           - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
       depends_on:
         - peer0.research.healthcare.com
         - peer1.research.healthcare.com
       networks:
           - healthNetwork
       deploy:
            mode: replicated
            replicas: 1
            restart_policy:
              condition: on-failure
            placement:
                constraints:
                    - node.hostname == $RESEARCH_HOSTNAME