version: '2'

volumes: 
    orderer.healthcare.com:

networks:
    healthNetwork:

services:

    orderer.healthcare.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer.healthcare.com
        environment:
            - ORDERER_HOST=orderer.healthcare.com
        volumes:
            - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls:/var/hyperledger/tls
            - ../channel-artifacts/:/var/hyperledger/configs
        networks:
          - healthNetwork
        ports:
          - 7050:7050