# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.healthcare.com:
  peer0.hprovider.healthcare.com:
  peer1.hprovider.healthcare.com:
  peer0.research.healthcare.com:
  peer1.research.healthcare.com:

networks:
  healthNetwork:
services:
  ca.hprovider.healthcare.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hprovider.healthcare.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hprovider.healthcare.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hprovider.healthcare.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-tls/key.pem -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hprovider.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.hprovider.healthcare.com
    networks:
      - healthNetwork

  ca.research.healthcare.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.research.healthcare.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.research.healthcare.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.research.healthcare.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/research.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.research.healthcare.com
    networks:
      - healthNetwork

  orderer.healthcare.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.healthcare.com
    container_name: orderer.healthcare.com
    networks:
      - healthNetwork

  peer0.hprovider.healthcare.com:
    container_name: peer0.hprovider.healthcare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hprovider.healthcare.com
    networks:
      - healthNetwork

  peer1.hprovider.healthcare.com:
    container_name: peer1.hprovider.healthcare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hprovider.healthcare.com
    networks:
      - healthNetwork

  peer0.research.healthcare.com:
    container_name: peer0.research.healthcare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.research.healthcare.com
    networks:
      - healthNetwork

  peer1.research.healthcare.com:
    container_name: peer1.research.healthcare.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.research.healthcare.com
    networks:
      - healthNetwork
