NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.hp2.healthcare.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.hp2.healthcare.com-cert.pem
    OrganizationalUnitIdentifier: peer
